# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c5e77fdf1313cd8a259e32e5ba3d0429df8a1740a53f728e02eea3b8504dabbbdde3561c09e0737292244a48de21f90879df57478cf630160e167f2b8e9773a

test:
  secret_key_base: ae0f1c6f84ebcf64fadbea643b360f4b36132d612ca995488d490ee8f451dc8200be4700ea3c0b677cc760f18c4943b6dc43334c22114d92f9d4f0a0f36289d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
